### ISSUE TITLE
请问这个运行效果是怎样的?

### ISSUE THREAD

**Issue by yigiuwoligiao** [william-sv/DouYinVideoDown#1]

**Comment by yigiuwoligiao** [comment]
我初学菜鸟   运行代码后输入了分享的抖音链接,大概是这个格式https://v.douyin.com/JeUKHSf/    然后浏览器打开了一个页面,但是好像没有下载的反馈什么的   是失败了吗?

**Comment by william-sv** [comment]
这个脚本执行后，会提示输入需要下载的视频链接，填入链接后点击回车会输出无水印版的地址，此时可以复制该地址到浏览器里进行下载，或者按照提示填写即将保存的视频的名字，会将视频下载至当前脚本文件夹下

**Comment by william-sv** [comment]
如果你使用的是 PyCharm，可以根据如下提示执行脚本：


1、安装相应的库，BeautifulSoup


2、执行脚本，根据提示输入相应的视频链接，解析成功后会输出相应的无水印链接地址，
 
3、输入即将保存的视频的名字


4、等待片刻后在该脚本文件夹下会下载好相应的视频

July 4, 2020 at 2:03 AM，学习真tm痛苦 <notifications@github.com> 写道：






我初学菜鸟 运行代码后输入了分享的抖音链接,大概是这个格式https://v.douyin.com/JeUKHSf/ 然后浏览器打开了一个页面,但是好像没有下载的反馈什么的 是失败了吗?
